version: "3"

services:
  php:
    container_name: php # 容器名称
    restart: always # 总是重启
    depends_on:
      # 依赖容器
      - mysql
    build: ./php #选择自己dockerfile的镜像
    # ports:
    #   - "9000:9000"
    links:
      - mysql:mysql
    volumes:
      - ~/docker-workspace/workspace/www:/usr/share/nginx/html
    logging:
      driver: json-file
      options:
        max-size: "2g" # 单个文件大小为200k
        max-file: "10" # 最多10个文件

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/docker-workspace/workspace/www:/usr/share/nginx/html
      - ~/docker-workspace/workspace/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ~/docker-workspace/workspace/conf/nginx/conf.d:/etc/nginx/conf.d:rw
      - ~/docker-workspace/workspace/etc/letsencrypt:/etc/letsencrypt:rw
    links:
      - php
    logging:
      driver: json-file
      options:
        max-size: "2g" # 单个文件大小为200k
        max-file: "10" # 最多10个文件

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ~/docker-workspace/workspace/etc/letsencrypt:/etc/letsencrypt
      - ~/docker-workspace/workspace/www:/var/www/certbot
    logging:
      driver: json-file
      options:
        max-size: "2g" # 单个文件大小为200k
        max-file: "10" # 最多10个文件

  mysql:
    image: mysql:8.0.33-debian
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "3306:3306"
    volumes:
      - ~/docker-workspace/workspace/mysql/mysql:/var/lib/mysql #抛出文件，防止数据库丢失
      - ~/docker-workspace/workspace/mysql/conf.d:/etc/mysql/conf.d:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 200M
    logging:
      driver: json-file
      options:
        max-size: "2g" # 单个文件大小为200k
        max-file: "10" # 最多10个文件

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: [ --auth ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ~/docker-workspace/workspace/mongodb/data/db:/data/db #抛出文件，防止数据库丢失

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/

  redis:
    image: redis
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ~/docker-workspace/workspace/redis/redis.conf:/etc/redis/redis.conf:ro
      - ~/docker-workspace/workspace/redis/data:/data:rw
    command: redis-server /etc/redis/redis.conf --appendonly yes --slave-read-only no

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ~/docker-workspace/workspace/apisix-dashboard/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.3.0-debian}
    container_name: apisix
    restart: always
    volumes:
      # - ~/docker-workspace/workspace/apisix:/usr/local/apisix
    - ~/docker-workspace/workspace/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    - ~/docker-workspace/workspace/apisix/logs:/usr/local/apisix/logs

    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      # - "9091:9091/tcp"
      # - "9443:9443/tcp"
      # - "9092:9092/tcp"

  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd
    restart: always
    volumes:
      - ~/docker-workspace/workspace/etcd:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"

  tenant-rpc:
    image: return1996/tenant-rpc:latest
    container_name: tenant-rpc
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/tenant-rpc/etc:/app/etc:ro
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd
    networks:
      - default

  admin-rpc:
    image: return1996/admin-rpc:latest
    container_name: admin-rpc
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/admin-rpc/data:/app/data:ro
      - ~/docker-workspace/workspace/app/admin-rpc/etc:/app/etc:ro
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd

  user-rpc:
    image: return1996/user-rpc:latest
    container_name: user-rpc
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/user-rpc/etc:/app/etc:ro
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd

  portal-rpc:
    image: return1996/portal-rpc:latest
    container_name: portal-rpc
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/portal-rpc/etc:/app/etc:ro
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd

  lowcode-api:
    image: return1996/lowcode-api:latest
    container_name: lowcode-api
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/lowcode-api/etc:/app/etc:ro
    ports:
      - "8600:8600"
    depends_on:
      - mongo
      - redis
      - mysql
      - etcd
    links:
      - mongo
      - redis
      - mysql
      - etcd
      - user-rpc
      - tenant-rpc

  tenant-api:
    image: return1996/tenant-api:latest
    container_name: tenant-api
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/tenant-api/etc:/app/etc:ro
    ports:
      - "8700:8700"
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd
      - admin-rpc
      - user-rpc
      - portal-rpc

  admin-api:
    image: return1996/admin-api:latest
    container_name: admin-api
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/admin-api/data:/app/data:ro #
      - ~/docker-workspace/workspace/app/admin-api/etc:/app/etc:ro
      - ~/docker-workspace/workspace/app/admin-api/public:/app/public:rw
    ports:
      - "8800:8800"
    depends_on:
      - mysql
      - etcd
    links:
      - mysql
      - etcd

  user-api:
    image: return1996/user-api:latest
    container_name: user-api
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/user-api/etc:/app/etc:ro
    ports:
      - "8801:8801"
    depends_on:
      - mysql
    links:
      - mysql
      - etcd
      - admin-rpc
      - user-rpc

  portal-api:
    image: return1996/portal-api:latest
    container_name: portal-api
    restart: always
    volumes:
      - ~/docker-workspace/workspace/app/portal-api/etc:/app/etc:ro
    ports:
      - "8802:8802"
    depends_on:
      - mysql
    links:
      - mysql
      - etcd
      - user-rpc

  # wechat-api:
  #   image: return1996/wechat-api:latest
  #   container_name: wechat-api
  #   restart: always
  #   volumes:
  #     - ~/docker-workspace/workspace/app/wechat-api/data:/app/data:rw #
  #     - ~/docker-workspace/workspace/app/wechat-api/etc:/app/etc:ro
  #     - ~/docker-workspace/workspace/app/wechat-api/public:/app/public:rw
  #   ports:
  #     - "8803:8803"
  #   depends_on:
  #     - mysql
  #     - etcd
  #   links:
  #     - mysql
  #     - etcd

  zerocmf-node:
    image: return1996/zerocmf-node:latest
    # build: ./node #选择自己dockerfile的镜像
    container_name: zerocmf-node
    ports:
      - "3000:3000"
    depends_on:
      - apisix
    links:
      - apisix
  # node-website:
  #   image: node:16.19.0-alpine
  #   # build: ./node #选择自己dockerfile的镜像
  #   container_name: node-website
  #   volumes:
  #     - ~/docker-workspace/workspace/node:/root/workspace:rw
  #   command: /bin/sh -c "cd /root/workspace && npm install && node server.js"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - portal-api
  #   links:
  #     - apisix
